### ISSUE TITLE
Not parsing Latest Query Log files from Aura (mar 2023) 

### ISSUE THREAD

**Issue by kvegter** [kvegter/query-analyzer-app#9]
When a downloaded query log file from Aura is uploaded in the tool the file does not get parsed 
the console log shows this:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at QueryAnalyzer._parseAuraJSONLine (qanalyzer.js:2826:39)
    at QueryAnalyzer.__analyseLogEntry (qanalyzer.js:1448:29)
    at QueryAnalyzer._analyseLog (qanalyzer.js:1613:22)
    at QueryAnalyzer.analyseFile (qanalyzer.js:1062:29)
    at reader.onload (index.html?url=neo4j%3A%2F%2Flocalhost&user=neo4j:223:21)```

**Comment by kvegter** [comment]
This is fixed in 1.0.10.
